# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    invoice_issuer:
        name: '%env(INVOICE_ISSUER_NAME)%'
        oib: '%env(INVOICE_ISSUER_OIB)%'
        pdv: '%env(INVOICE_ISSUER_PDV)%'
        address: '%env(INVOICE_ISSUER_ADDRESS)%'
        email: '%env(INVOICE_ISSUER_EMAIL)%'
        phone: '%env(INVOICE_ISSUER_PHONE)%'
    email_brand:
        website: 'https://steelcode.dev'
        instagram: 'https://www.instagram.com/steelcodedev'
        facebook: 'https://www.facebook.com/steelcodedev'
        linkedin: 'https://linkedin.com/company/steelcodedev/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Integration\SecretCipher:
        arguments:
            $appSecret: '%kernel.secret%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
