# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    rate_limiter:
        password_reset:
            policy: sliding_window
            limit: 3
            interval: '1 hour'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        name: steelcode_session
        cookie_httponly: true
        cookie_samesite: lax
        cookie_secure: auto

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
